name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "Hello world!"
          echo "what's up"
      - name: print goodbye
        run: echo "Goodbye"
